<template>
  <v-card
    class="mx-auto"
  >
    <v-row
      v-for="(time, i) in 4"
      :key="i"
    >
      <v-col cols="12">
        <v-divider />
        <v-list-group
          :value="true"
        >
          <template v-slot:activator>
            <v-list-item-title>{{i+1}}限</v-list-item-title>
          </template>
          <v-col cols="12">
            <v-select
              :items="subject"
              clearable
              filled
              label="科目"
            >
            </v-select>
            <v-select
              :items="teacher"
              clearable
              filled
              label="担当教諭"
            >
            </v-select>
            <v-autocomplete
              item-text="room"
              :items="classroom"
              clearable
              filled
              label="教室"
            >
            </v-autocomplete>
          </v-col>
        </v-list-group>
      </v-col>
    </v-row>
  </v-card>
</template>

<script>
  export default {
    data: () => ({
      subject: [
        ['アプリケーション開発技術'],
        ['卒業研究'],
      ],
      
      teacher: [
        ['切口先生'],
        ['坂中先生'],
        ['福留先生'],
        ['永谷先生'],
      ],
      classroom:[
        {
          room:'101',
          floor:'1'
        },
        {
          room:'102',
          floor:'1'
        },
        {
          room:'104',
          floor:'1'
        },
        {
          room:'201',
          floor:'2'
        },
        {
          room:'202',
          floor:'2'
        },
        {
          room:'203',
          floor:'2'
        },
        {
          room:'進路相談室',
          floor:'2'
        },
        {
          room:'図書室',
          floor:'2'
        },
        {
          room:'301',
          floor:'3'
        },
        {
          room:'302',
          floor:'3'
        },
        {
          room:'303',
          floor:'3'
        },
        {
          room:'304',
          floor:'3'
        },
        {
          room:'305',
          floor:'3'
        },
        {
          room:'401',
          floor:'4'
        },
        {
          room:'402',
          floor:'4'
        },
        {
          room:'403',
          floor:'4'
        },
        {
          room:'404',
          floor:'4'
        }
      ]
    }),
  }
</script>