<template>
  <v-card
    class="mx-auto"
  >
      <v-list-group
        :value="true"
      >
        <template v-slot:activator>
          <v-list-item-title>1限</v-list-item-title>
        </template>
        <v-col cols="12">
        <v-select
          :items="subject"
          clearable
          filled
          label="科目"
        >
        </v-select>
        <v-select
          :items="teacher"
          clearable
          filled
          label="担当教諭"
        >
        </v-select>
        <v-row v-for="(classrooms,i) in  classroom" :key=i>
          <v-col cols="1">
            <v-checkbox
              v-model="enabled"
              hide-details
            ></v-checkbox>
          </v-col>
          <v-col cols="11">
            <v-select
              item-text="room"
              :items="classroom"
              clearable
              filled
              :disabled="!enabled"
              label="1階教室"
            >
            </v-select>
          </v-col>
        </v-row>
        </v-col>
      </v-list-group>
  </v-card>
</template>

<script>
  export default {
    data: () => ({
      subject: [
        ['アプリケーション開発技術'],
        ['卒業研究'],
      ],
      
      teacher: [
        ['切口先生'],
        ['坂中先生'],
        ['福留先生'],
        ['永谷先生'],
      ],
      classroom:[
        {
          room:'101',
          floor:'1'
        },
        {
          room:'102',
          floor:'1'
        },
        {
          room:'104',
          floor:'1'
        },
        {
          room:'201',
          floor:'2'
        },
        {
          room:'202',
          floor:'2'
        },
        {
          room:'203',
          floor:'2'
        },
        {
          room:'進路相談室',
          floor:'2'
        },
        {
          room:'図書室',
          floor:'2'
        },
        {
          room:'301',
          floor:'3'
        },
        {
          room:'302',
          floor:'3'
        },
        {
          room:'303',
          floor:'3'
        },
        {
          room:'304',
          floor:'3'
        },
        {
          room:'305',
          floor:'3'
        },
        {
          room:'401',
          floor:'4'
        },
        {
          room:'402',
          floor:'4'
        },
        {
          room:'403',
          floor:'4'
        },
        {
          room:'404',
          floor:'4'
        }
      ],
      enabled: false,
    }),
  }
</script>