<template>
<div>
<h1 class="pt-4">
    <v-icon
    size="1.5em"
    color="blue-grey darken-3">
      mdi-account-key
    </v-icon>
    &emsp;管理者メニュー</h1>
    <v-divider></v-divider>
<v-row
    style="height: 520px"
    justify="center"
    align-content="center"
    
>
<v-col
    cols="3">
<v-card
 elevation="0"
>
    <v-btn
        color="accent"
        elevation="12"
        width="550"
        height="120"
        to="/teacher/RoomSchedule"
><h2>教室スケジュール管理</h2></v-btn>
</v-card>
<br>
<v-card
 elevation="0"
>
    <v-btn
        color="accent"
        elevation="12"
        width="550"
        height="120"
        to="/teacher/TimeSchedule"
><h2>時間割管理</h2></v-btn>
</v-card>
<br>
<v-card
 elevation="0"
>
    <v-btn
        color="accent"
        elevation="12"
        width="550"
        height="120"
        to="/teacher/GroupAdmin"
><h2>グループ管理</h2></v-btn>
</v-card>
</v-col>
<v-spacer></v-spacer>
<v-col
    cols="4.5">
<v-card
 elevation="0"
>
    <v-btn
        color="accent"
        elevation="12"
        width="550"
        height="120"
        to="/teacher/StudentGroupMember"
><h2>学生管理</h2></v-btn>
</v-card>
<br>
<v-card
 elevation="0"
>
    <v-btn
        color="accent"
        elevation="12"
        width="550"
        height="120"
        to="/teacher/EventManage"
><h2>イベント管理</h2></v-btn>
</v-card>
<br>
<v-card
 elevation="0"
>
    <v-btn
        color="accent"
        elevation="12"
        width="550"
        height="120"
></v-btn>
</v-card>
</v-col>
</v-row>
</div>
</template>