<template>
    <v-card color="accent">
        <v-card-title>イベントスケジュール</v-card-title>
        <v-col>
        <v-card>
          <v-card-subtitle>国家試験</v-card-subtitle>
          <v-card-text>あと2時間</v-card-text>
        </v-card>
        </v-col>
        <v-divider></v-divider>
        <v-col>
        <v-card>
          <v-card-subtitle>卒業研究発表</v-card-subtitle>
          <v-card-text>あと6時間</v-card-text>
        </v-card>
        </v-col>
        <v-divider></v-divider>
        <v-col>
        <v-card>
          <v-card-subtitle>卒業</v-card-subtitle>
          <v-card-text>あと10時間</v-card-text>
        </v-card>
        </v-col>
    </v-card>
</template>